version: "3.8"
services:
  postgres:
    image: postgres:13
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  # panel:
  #   image: ghcr.io/stevensblueprint/aad-admin:latest
  #   restart: on-failure
  #   labels:
  #     - "com.centurylinklabs.watchtower.scope=aad"
  #   networks:
  #     aad:
  #       ipv4_address: 10.10.2.3
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     DATABASE_URL: ${POSTGRES_URL}
  #     NEXTAUTH_URL: ${NEXTAUTH_URL}
  #     NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
  #     GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
  #     GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
  #   depends_on:
  #     - postgres
  wt:
    image: containrrr/watchtower
    labels:
      - "com.centurylinklabs.watchtower.scope=aad"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --scope aad

volumes:
  postgres_data:
networks:
  aad:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.2.0/24
          gateway: 10.10.2.1