name: Build site

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Build site
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
      - run: |
          cp .env.example .env
          pnpm i
          pnpm build
