name: build and publish dockerfile
on:
  push:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: "JonMike8"
        password: ${{ secrets.ACCESS_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ghcr.io/stevensblueprint/aad-admin:${{ github.sha }}
          ghcr.io/stevensblueprint/aad-admin:latest
