name: Lint/Format Check

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run ESLint Check
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "pnpm"
      - run: |
          pnpm i
          cp .env.example .env
          pnpm lint

  format:
    runs-on: ubuntu-latest
    name: Run Format Check
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "pnpm"
      - run: |
          pnpm i --frozen-lockfile
          pnpm format:check
