name: Lint/Format Check

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run ESLint Check
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm run lint

  format:
    runs-on: ubuntu-latest
    name: Run Format Check
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Run Format
        run: pnpm format:check
